version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx
    container_name: "cloud-mail-ru-server"
    depends_on:
      - app
    ports:
      - "8065:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cloud-mail-ru-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: "cloud-mail-ru-app"
    environment:
      #XDEBUG_CONFIG: "remote_host=192.168.4.1 remote_enable=1"
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - cloud-mail-ru-network

#Docker Networks
networks:
  cloud-mail-ru-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/28
