version: '3.8'

services:

  cloud-mail-ru-webserver:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    container_name: "cloud-mail-ru-webserver"
    depends_on:
      - cloud-mail-ru-app
    ports:
      - "${APP_WEB_PORT}:80"
    environment:
      PHP_FPM_PORT: ${PHP_FPM_PORT}
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template
    networks:
      - cloud-mail-ru-network

  cloud-mail-ru-app:
    build:
      context: ..
      dockerfile: php-fpm/Dockerfile
    container_name: "cloud-mail-ru-app"
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=${SUBNET_IP}.1"
      PHP_IDE_CONFIG: "serverName=cloud-mail-ru-app"
    ports:
      - "${PHP_FPM_PORT}:9000"
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cloud-mail-ru-network

networks:
  cloud-mail-ru-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}.0/28
